/**
 * @module baselineService
 * Fetches and parses the pre-built daily baseline JSON that ships the full
 * ~7,000-item GE catalogue with latest prices, buy limits, and high alch
 * values — generated by CI (GitHub Actions) once per day.
 *
 * The baseline eliminates the need for API-heavy seed fetches at startup,
 * reducing cold-start time from ~30–60 s to ~1–2 s.
 */

import type { WeirdGloopPriceRecord } from "./types";

/** Maximum age (ms) before the baseline is considered stale. */
const MAX_AGE_MS = 48 * 60 * 60 * 1000; // 48 hours

/** Expected format version of the baseline file. */
const EXPECTED_VERSION = 3;

/** Shape of a single item in the baseline JSON `items` object. */
interface BaselineItem {
  id: number;
  price: number;
  volume: number;
  timestamp: string;
  buyLimit?: number;
  highAlch?: number | false;
}

/** Top-level shape of `data/baseline.json`. */
interface BaselinePayload {
  version: number;
  generatedAt: string;
  itemCount: number;
  items: Record<string, BaselineItem>;
}

/**
 * Fetch the baseline JSON and convert it to a `Map<string, WeirdGloopPriceRecord>`.
 *
 * @returns A map of item name → price record, or `null` on any failure
 *          (404, network error, parse error, stale data). Never throws.
 */
export async function loadBaseline(): Promise<Map<string, WeirdGloopPriceRecord> | null> {
  try {
    const res = await fetch("./data/baseline.json");
    if (!res.ok) {
      console.warn(`[BaselineService] Fetch failed: HTTP ${res.status}`);
      return null;
    }

    const payload: BaselinePayload = await res.json();

    // Version check
    if (payload.version !== EXPECTED_VERSION) {
      console.warn(`[BaselineService] Version mismatch: expected ${EXPECTED_VERSION}, got ${payload.version}`);
      return null;
    }

    // Staleness check — reject baselines older than 48 hours
    const generatedAt = new Date(payload.generatedAt).getTime();
    if (Number.isNaN(generatedAt) || Date.now() - generatedAt > MAX_AGE_MS) {
      console.warn(
        `[BaselineService] Baseline too old (generated ${payload.generatedAt}). Falling back to seeds.`
      );
      return null;
    }

    // Convert to Map<string, WeirdGloopPriceRecord>
    const map = new Map<string, WeirdGloopPriceRecord>();
    for (const [name, item] of Object.entries(payload.items)) {
      const record: WeirdGloopPriceRecord = {
        id: item.id,
        price: item.price,
        volume: item.volume,
        timestamp: item.timestamp,
      };
      if (item.buyLimit !== undefined) record.buyLimit = item.buyLimit;
      if (item.highAlch !== undefined) record.highAlch = item.highAlch;
      map.set(name, record);
    }

    console.log(
      `[BaselineService] Loaded baseline: ${map.size} items (generated ${payload.generatedAt}).`
    );
    return map;
  } catch (err) {
    console.warn("[BaselineService] Failed to load baseline:", err);
    return null;
  }
}
