/**
 * @module services/seedItems
 * Curated seed list of heavily-traded RS3 items used to bootstrap the
 * database on first run when the daily baseline is unavailable.
 *
 * These names must be **exact** canonical RS Wiki titles.
 * Verify via `https://api.weirdgloop.org/exchange/history/rs/last90d?name=<encoded>`
 * before adding new entries.
 */

export const SEED_ITEMS: string[] = [
  // ── Rares & Discontinued ──────────────────────────────────────────────
  "Blue partyhat",
  "Red partyhat",
  "Green partyhat",
  "Yellow partyhat",
  "Purple partyhat",
  "White partyhat",
  "Christmas cracker",
  "Santa hat",
  "Green hallowe'en mask",
  "Red hallowe'en mask",
  "Blue hallowe'en mask",
  "Easter egg",
  "Pumpkin",
  "Disk of returning",
  "Black Santa hat",
  "Fish mask",


  // ── High-volume Skilling Supplies ─────────────────────────────────────
  "Raw shark",
  "Shark",
  "Raw rocktail",
  "Rocktail",
  "Raw sailfish",
  "Sailfish",
  "Raw lobster",
  "Lobster",
  "Raw swordfish",
  "Swordfish",
  "Grimy dwarf weed",
  "Clean dwarf weed",
  "Grimy lantadyme",
  "Clean lantadyme",
  "Grimy torstol",
  "Clean torstol",
  "Grimy snapdragon",
  "Clean snapdragon",
  "Grimy ranarr",
  "Clean ranarr",
  "Grimy kwuarm",
  "Clean kwuarm",
  "Grimy cadantine",
  "Clean cadantine",
  "Grimy avantoe",
  "Clean avantoe",
  "Grimy toadflax",
  "Clean toadflax",
  "Grimy irit",
  "Clean irit",
  "Grimy spirit weed",
  "Clean spirit weed",
  "Magic logs",
  "Elder logs",
  "Yew logs",
  "Maple logs",
  "Willow logs",
  "Coal",
  "Mithril ore",
  "Adamantite ore",
  "Luminite",
  "Runite ore",
  "Gold ore",
  "Iron ore",
  "Silver ore",
  "Copper ore",
  "Tin ore",
  "Banite ore",
  "Orichalcite ore",
  "Drakolith",
  "Phasmatite",
  "Necrite ore",
  "Light animica",
  "Dark animica",
  "Pure essence",
  "Rune essence",
  "Flax",
  "Bowstring",
  "Uncut diamond",
  "Uncut ruby",
  "Uncut emerald",
  "Uncut sapphire",
  "Diamond",
  "Ruby",
  "Emerald",
  "Sapphire",
  "Crystal flask",
  "Potion flask",
  "Vial of water",
  "Feather",

  // ── Potions & Consumables ─────────────────────────────────────────────

  "Super restore (4)",
  "Prayer potion (4)",
  "Saradomin brew (4)",
  "Weapon poison+++ (4)",
  "Aggression potion (4)",
  "Super antifire (4)",
  "Prayer renewal (4)",
  "Extreme attack (4)",
  "Extreme strength (4)",
  "Extreme defence (4)",
  "Extreme magic (4)",
  "Extreme ranging (4)",
  "Super prayer (4)",
  "Summoning potion (4)",
  "Antifire (4)",
  "Super attack (4)",
  "Super strength (4)",
  "Super defence (4)",
  "Super magic potion (4)",
  "Super ranging potion (4)",

  "Rocktail soup",
  "Sailfish soup",
  "Summer pie",

  // ── Runes ─────────────────────────────────────────────────────────────
  "Blood rune",
  "Death rune",
  "Soul rune",
  "Nature rune",
  "Astral rune",
  "Law rune",
  "Fire rune",
  "Water rune",
  "Air rune",
  "Earth rune",
  "Body rune",
  "Mind rune",
  "Chaos rune",
  "Cosmic rune",
  "Mud rune",
  "Dust rune",
  "Lava rune",
  "Steam rune",
  "Smoke rune",
  "Mist rune",
  "Armadyl rune",

  // ── PvM Drops & Salvage ───────────────────────────────────────────────
  "Dragonfire shield",
  "Abyssal whip",
  "Dark bow",
  "Dragon Rider lance",
  "Noxious scythe",
  "Noxious staff",
  "Noxious longbow",
  "Ascension crossbow",
  "Virtus mask",
  "Virtus robe top",
  "Virtus robe legs",
  "Torva full helm",
  "Torva platebody",
  "Torva platelegs",
  "Pernix cowl",
  "Pernix body",
  "Pernix chaps",
  "Malevolent helm",
  "Malevolent cuirass",
  "Malevolent greaves",
  "Seren godbow",
  "Staff of Sliske",
  "Zaros godsword",
  "Praesul codex",
  "Inquisitor staff",
  "Masterwork platebody",
  "Masterwork platelegs",
  "Masterwork helm",
  "Masterwork boots",
  "Masterwork gloves",
  "Trimmed masterwork platebody",
  "Trimmed masterwork platelegs",
  "Trimmed masterwork helm",
  "Trimmed masterwork boots",
  "Trimmed masterwork gloves",
  "Eldritch crossbow",
  "Blightbound crossbow",
  "Fractured Staff of Armadyl",
  "Scripture of Jas",
  "Scripture of Wen",
  "Scripture of Ful",
  "Cinderbane gloves",
  "Laceration boots",
  "Fleeting boots",
  "Blast diffusion boots",
  "Essence of Finality amulet",
  "Amulet of souls",
  "Reaper necklace",
  "Deathtouch bracelet",
  "Ring of death",
  "Luck of the Dwarves",

  // ── Summoning & Misc ──────────────────────────────────────────────────
  "Spirit shards",
  "Pouch",

  "Pack yak pouch",
  "Water talisman",
  "Fire talisman",
  "Yak-hide",
  "Unicorn horn",
  "Swamp tar",

  // ── Alchable / Margin Items ───────────────────────────────────────────
  "Battlestaff",
  "Onyx",
  "Uncut onyx",
  "Onyx bolts (e)",
  "Rune bar",
  "Adamant bar",
  "Mithril bar",
  "Steel bar",
  "Iron bar",
  "Bronze bar",
  "Gold bar",
  "Bane bar",
  "Elder rune bar",
  "Orikalkum bar",
  "Necronium bar",
  "Hydrix",
  "Uncut dragonstone",
  "Dragonstone",
  "Bond",
  "Cannonball",
  "Broad arrowheads",
  "Dragon bones",
  "Frost dragon bones",
  "Dinosaur bones",
  "Reinforced dragon bones",
  "Dagannoth bones",
  "Infernal ashes",
  "Dragon arrowheads",
  "Rune arrowheads",
  "Adamant arrowheads",
  "Black dragonhide",
  "Royal dragonhide",
  "Green dragonhide",
  "Blue dragonhide",
  "Red dragonhide",
  "Rune platebody",
  "Rune platelegs",
  "Dragon platelegs",
  "Dragon plateskirt",
  "Dragon helm",
];
